In [1]:
import numpy as np

In [2]:
# Create numpy arrays from python list

np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [5]:
a1 = np.array([1,23, 24, 25, 26,],dtype='float32') # có thể ép kiểu cho các thành phần trong mảng

In [6]:
a1

array([ 1., 23., 24., 25., 26.], dtype=float32)

In [7]:
type(a1)

numpy.ndarray

In [8]:
a1.shape # shape của array

(5,)

In [9]:
a1.ndim # số chiều của arr

1

In [11]:
a1.dtype

dtype('float32')

In [12]:
a1.size # kích thước

5

# Create numpy arrays

 - Trong zeros function : 
  + sử dụng order cho việc sắp xếp các phần tử trong mảng
  + like là tạo ra một mảng có cùng kích thước  ,kiểu dữ liệu và thứ tự mảng với mảng chỉ định

In [15]:
np.zeros(shape = [4,5], dtype = np.float, order = 'C',like	= np.zeros(shape = [4,5], dtype = np.float, order = 'C'))

/tmp/ipykernel_21937/721104848.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros(shape = [4,5], dtype = np.float, order = 'C',like	= np.zeros(shape = [4,5], dtype = np.float, order = 'C'))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones(shape=(3, 4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
np.arange(start= 3, stop= 10, step= 2)

array([3, 5, 7, 9])

In [20]:
np.full(shape=(5,7),dtype=float,fill_value=9.8)

array([[9.8, 9.8, 9.8, 9.8, 9.8, 9.8, 9.8],
       [9.8, 9.8, 9.8, 9.8, 9.8, 9.8, 9.8],
       [9.8, 9.8, 9.8, 9.8, 9.8, 9.8, 9.8],
       [9.8, 9.8, 9.8, 9.8, 9.8, 9.8, 9.8],
       [9.8, 9.8, 9.8, 9.8, 9.8, 9.8, 9.8]])

In [22]:
np.linspace(start= 0, stop= 1, num= 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [23]:
## random function

np.random.random(size=10)

array([0.73234237, 0.5419469 , 0.13648334, 0.09943043, 0.82914235,
       0.09682633, 0.00659121, 0.68410312, 0.03992926, 0.02825104])

In [25]:
np.random.seed(0)
np.random.random((4,5))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215]])

In [28]:
np.random.normal(0,1,(3,4)) 
# Giá trị trung bình bằng 0
# Độ lệch chuẩn bằng 1
# vector (3 *4)

array([[-1.04855297, -1.42001794, -1.70627019,  1.9507754 ],
       [-0.50965218, -0.4380743 , -1.25279536,  0.77749036],
       [-1.61389785, -0.21274028, -0.89546656,  0.3869025 ]])

In [30]:
np.random.randint(1,22,size=(4,5))
#min = 1;
#max = 22;
#shape = (4,5)

array([[ 4,  3, 11, 14, 17],
       [ 8, 10,  1, 11, 19],
       [12,  3,  3,  4,  4],
       [19, 15,  4, 21, 18]])

In [31]:
np.random.rand(4,4)

array([[0.50896896, 0.91672295, 0.92115761, 0.08311249],
       [0.27771856, 0.0093567 , 0.84234208, 0.64717414],
       [0.84138612, 0.26473016, 0.39782075, 0.55282148],
       [0.16494046, 0.36980809, 0.14644176, 0.56961841]])

In [36]:
# Concatenation and splitting 
x = np.array([1, 2, 3])
y = np.array([1, 2, 6])

In [39]:
result = np.concatenate((x, y))

In [40]:
result

array([1, 2, 3, 1, 2, 6])

In [47]:
grid = np.zeros((4,5),dtype=float)
grid2 = np.random.randint(1,22,size=(4,5))

In [48]:
grid
grid2

array([[12, 14, 17,  9,  9],
       [20,  9,  3, 21,  4],
       [13, 15,  1,  5,  4],
       [14, 12, 14, 14, 12]])

In [49]:
d = np.concatenate((grid,grid2))

In [50]:
d

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [12., 14., 17.,  9.,  9.],
       [20.,  9.,  3., 21.,  4.],
       [13., 15.,  1.,  5.,  4.],
       [14., 12., 14., 14., 12.]])

In [55]:
z = np.concatenate((grid,grid2),axis=1) # nối theo chiều ngang

In [56]:
z

array([[ 0.,  0.,  0.,  0.,  0., 12., 14., 17.,  9.,  9.],
       [ 0.,  0.,  0.,  0.,  0., 20.,  9.,  3., 21.,  4.],
       [ 0.,  0.,  0.,  0.,  0., 13., 15.,  1.,  5.,  4.],
       [ 0.,  0.,  0.,  0.,  0., 14., 12., 14., 14., 12.]])

In [62]:
#vstack
p = np.array([1,2,3])
o = np.array([[1,2,3],[9,8,7]])
np.vstack((p,o))

array([[1, 2, 3],
       [1, 2, 3],
       [9, 8, 7]])

In [63]:
#hstack
y = np.array([[99],[99]])

np.hstack((y,o))

array([[99,  1,  2,  3],
       [99,  9,  8,  7]])

In [65]:
#split
np.split(o,[2,5])

[array([[1, 2, 3],
        [9, 8, 7]]),
 array([], shape=(0, 3), dtype=int64),
 array([], shape=(0, 3), dtype=int64)]

In [66]:
dog_heights =[600,470,170,430,300]
dog_heights = np.array(dog_heights)

In [67]:
#Độ lệch chuẩn

np.std(dog_heights)

147.32277488562318

In [68]:
#full size
np.var(dog_heights)

21704.0

In [69]:
# Độ lệch chuẩn
np.sqrt(np.var(dog_heights))

147.32277488562318