In [45]:
import pandas as pd
import numpy as np

# 1. Problem definition - Xác định vấn đề
 - Goal: predict the sales price for each house

In [46]:
data = pd.read_csv("./Data/train.csv")

In [47]:
data.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape   
0   1          60       RL         65.0     8450   Pave   NaN      Reg  \
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold   
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2  \
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [48]:
data.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

# 2. Features selection - Tìm đặc trưng
- Choose feature to train ML Model
- Need to use 'Feature Engineering' to identify features needed to train

In [49]:
features = ["LotArea", "YearBuilt", "1stFlrSF", "2ndFlrSF", "FullBath", "BedroomAbvGr", "TotRmsAbvGrd"]

# 3. Splitting the datasets - Chia dữ liệu
 - data: dataset
 - x : data[features]
 - y: target variable saleprice

In [50]:
x = data[features]
y = data['SalePrice']

In [51]:
data.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape   
0   1          60       RL         65.0     8450   Pave   NaN      Reg  \
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold   
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2  \
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [52]:
x.head()

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr   
0     8450       2003       856       854         2             3  \
1     9600       1976      1262         0         2             3   
2    11250       2001       920       866         2             3   
3     9550       1915       961       756         1             3   
4    14260       2000      1145      1053         2             4   

   TotRmsAbvGrd  
0             8  
1             6  
2             6  
3             7  
4             9

In [53]:
y.head()

0    208500
1    181500
2    223500
3    140000
4    250000
Name: SalePrice, dtype: int64

In [54]:
# x,y -> x_train, y_train, x_valid, y_valid


from sklearn.model_selection import  train_test_split

x_train, x_valid, y_train, y_valid = train_test_split(x,y,train_size=0.8,test_size=0.2,random_state=0) #0.8 <=> 80% train, 20% test

In [55]:
x_train

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr   
618     11694       2007      1828         0         2             3  \
870      6600       1962       894         0         1             2   
92      13360       1921       964         0         1             2   
817     13265       2002      1689         0         2             3   
302     13704       2001      1541         0         2             3   
...       ...        ...       ...       ...       ...           ...   
763      9430       1999      1268      1097         2             3   
835      9600       1950      1067         0         2             2   
1216     8930       1978      1318       584         2             4   
559      3196       2003      1557         0         2             2   
684     16770       1998      1195       644         2             4   

      TotRmsAbvGrd  
618              9  
870              5  
92               5  
817              7  
302              6  
...            ...  
763              8  
835              4  
1216             8  
559              7  
684              7  

[1168 rows x 7 columns]

In [56]:
x_valid

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr   
529     32668       1957      2515         0         3             4  \
491      9490       1941       958       620         1             3   
459      7015       1950       979       224         1             3   
279     10005       1977      1156       866         2             4   
655      1680       1971       525       567         1             3   
...       ...        ...       ...       ...       ...           ...   
326     10846       1993      1719         0         1             1   
440     15431       2008      2402         0         2             2   
1387     8520       1916      1664       862         2             5   
1323     5330       1940       708         0         1             2   
61       7200       1920       581       530         1             3   

      TotRmsAbvGrd  
529              9  
491              5  
459              5  
279              8  
655              6  
...            ...  
326              6  
440             10  
1387            10  
1323             5  
61               6  

[292 rows x 7 columns]

In [57]:
x.shape

(1460, 7)

In [58]:
x_valid.shape

(292, 7)

In [59]:
data.shape

(1460, 81)

# 4. Training machine model 


In [60]:
from sklearn.tree import DecisionTreeRegressor

dt_model = DecisionTreeRegressor(random_state=1)


In [61]:
#Fit training data into model
dt_model.fit(x_train, y_train)

DecisionTreeRegressor(random_state=1)

In [62]:
y_pred = dt_model.predict(x_valid.head())

In [63]:
y_pred

array([335000., 140200., 119000., 207500., 112000.])

In [64]:
pd.DataFrame({'y':y_valid.head(),'y_pred:':y_pred})

y   y_pred:
529  200624  335000.0
491  133000  140200.0
459  110000  119000.0
279  192000  207500.0
655   88000  112000.0

In [65]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor

rf_model = RandomForestRegressor(random_state=1)
rf_model.fit(x_train, y_train)

RandomForestRegressor(random_state=1)

In [66]:
rf_model.predict(x_valid)

array([271690.        , 155039.        , 122024.        , 188915.        ,
        91147.        ,  88533.2       , 240518.24      , 126286.        ,
       624269.12      , 174312.25333333, 209138.46      , 147714.5       ,
       233088.25      , 123139.5       , 140503.75      , 139187.        ,
       232538.3       , 134260.        , 145952.24      , 130562.05      ,
       129304.53      , 147179.68333333, 112355.46      , 183320.22      ,
       153926.5       , 182853.57      , 176891.        ,  86320.        ,
       308784.98      , 112746.        , 141734.5       , 190094.        ,
       124460.65      , 280081.94      , 317780.6       , 179756.65      ,
       218512.64      , 118609.16      , 224329.28      , 304517.56      ,
       229449.        , 141422.15333333, 186872.35      , 302902.86      ,
       316105.83      , 139820.        , 105783.66      , 127933.25      ,
       165361.5       , 118615.5       , 314806.34      , 145952.75      ,
       168104.74      , 1

# Predict with a new input

In [67]:
rf_model.predict([[6969,2021,1000,800,4,5,8]])

/home/smithc3k56/.local/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([206158.4])

# 5.Model Evaluation - Đánh giá model


In [72]:
from sklearn.metrics import accuracy_score
accuracy_score = accuracy_score(y_valid[:5], y_pred[:5])
accuracy_score

0.0

In [71]:
#MSE - Giá trị càng nhỏ thì càng tốt 
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_valid[:5], y_pred[:5])
mse

3801199875.2